#!/usr/bin/env python3
"""
TCF · The Chamber · reading layer generator
(Phase 2, extended in Phase 3, adapted for tcf-chamber in Phase 4)

Reads  docs/data/chambers.json
       start/index.html             (only the "What" sentence, id="what-sentence")
Writes chambers/index.html          (list of every chamber)
       chambers/<id>.html           (one plain-HTML page per chamber)
       sitemap.xml                  (all public reading pages + every chamber)
       llms.txt                     (short guide for AI readers)

chambers.json is { "media_base": "...", "chambers": [...] } in this repo.
Video links are media_base + the file name of each chamber's video path,
so moving the videos later only needs media_base to change.

Plain static HTML: readable without JavaScript by people, screen readers and
AI readers. The immersive version stays at pages/page4.html.

Run from the repo root after chambers.json changes:
    python3 tools/build_chambers.py

Standard library only. Output is deterministic (no timestamps), so running it
twice with the same data produces no diff. chambers.json is only read, never
written.
"""
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'docs', 'data', 'chambers.json')
OUT = os.path.join(ROOT, 'chambers')

# The main TCF site (Door, Our Projects, About Us and the other doors live there).
MAIN_URL = 'https://chinsookling.github.io/the-Civilisation-field/'

# Same readable links as the main site; only 畫 The Chamber is local.
NAV = [
    ('Door', MAIN_URL + 'index.html'),
    ('琴 The Conservatory', MAIN_URL + 'pages/conservatory.html'),
    ('棋 Play', 'https://play.civilisationfield.com/'),
    ('書 The Library', MAIN_URL + 'index.html'),
    ('畫 The Chamber', '../pages/page4.html'),
    ('About Us', MAIN_URL + 'about/'),
]
IMMERSIVE = '../pages/page4.html'

# Footer on every reading page (Phase 3).
FOOTER = [
    ('Start Here', '../start/'),
    ('For AI readers', '../for-ai/'),
    ('License', '../license/'),
]

# Public base URL used in sitemap.xml and llms.txt.
# Change to 'https://chamber.civilisationfield.com/' once the domain points here (Phase 6).
BASE_URL = 'https://chinsookling.github.io/tcf-chamber/'
PLANNED_URL = 'https://chamber.civilisationfield.com/'

# Hand-written reading pages, relative to the site root.
READING_PAGES = ['start/', 'for-ai/', 'license/']
IMMERSIVE_PAGES = ['pages/page4.html', 'pages/skyhall.html', 'pages/accio.html']


def esc(s):
    return html.escape(str(s), quote=True)


# Display names (decided by Tuzi): the everyday names used across the site.
# The Scroll and Accio keep their own names (Fable / Bridge / Rex); not used here.
# Keys not listed fall back to the key in capitals (e.g. tcf -> TCF).
NAMES = {
    'tuzi': 'Tuzi', 'grok': 'Grok', 'gemini': 'Gemini', 'deepseek': 'DeepSeek',
    'gpt': 'GPT', 'copilot': 'Copilot', 'claude': 'Claude',
}


def name(key):
    return NAMES.get(str(key).lower(), str(key).upper())


def who(key):
    return esc(name(key))


def as_list(v):
    if not v:
        return []
    return v if isinstance(v, list) else [v]


MEDIA_BASE = ''


def video_url(path):
    """media_base + file name (see docs/scripts/chamber-data.js); unchanged if no media_base."""
    if not MEDIA_BASE or re.match(r'https?://', str(path)):
        return path
    return MEDIA_BASE.rstrip('/') + '/' + str(path).split('/')[-1]


def paragraphs(text):
    """Blank lines split paragraphs; single line breaks become <br>."""
    blocks = re.split(r'\n\s*\n', str(text).strip())
    return '\n'.join(
        '    <p>' + '<br>\n'.join(esc(line) for line in b.split('\n')) + '</p>'
        for b in blocks if b.strip())


def page(title, description, body):
    nav = ' ·\n    '.join('<a href="%s">%s</a>' % (esc(h), esc(l)) for l, h in NAV)
    foot = ' ·\n  '.join('<a href="%s">%s</a>' % (esc(h), esc(l)) for l, h in FOOTER)
    return """<!DOCTYPE html>
<!-- Generated by tools/build_chambers.py from docs/data/chambers.json. Do not edit by hand. -->
<html lang="zh-Hant">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s</title>
<meta name="description" content="%s">
<link rel="icon" type="image/svg+xml" href="../assets/favicon.svg">
<link rel="stylesheet" href="../docs/styles/field-tokens.css">
<link rel="stylesheet" href="../docs/styles/tcf-reading.css">
</head>
<body class="tcf-reading">
<header class="tcf-reading__nav">
  <nav aria-label="The Civilisation Field sections">
    %s
  </nav>
</header>
<main class="tcf-reading__main">
%s
</main>
<footer class="tcf-reading__footer">
  %s
</footer>
</body>
</html>
""" % (esc(title), esc(description), nav, body, foot)


def chamber_page(c, prev_c, next_c):
    cid, zh, en = c['id'], c['name_zh'], c['name_en']
    parts = []
    parts.append('<p class="tcf-reading__crumb"><a href="index.html">All chambers</a> · '
                 '<a href="%s">Enter the immersive chamber</a></p>' % IMMERSIVE)
    parts.append('<article>')
    parts.append('  <h1><span class="tcf-reading__zh">%s</span> '
                 '<span class="tcf-reading__en" lang="en">%s</span></h1>' % (esc(zh), esc(en)))
    parts.append('  <dl class="tcf-reading__meta">\n'
                 '    <dt>Chamber</dt><dd>%s</dd>\n'
                 '    <dt>Date</dt><dd><time datetime="%s">%s</time></dd>\n'
                 '    <dt>Created by</dt><dd>%s</dd>\n'
                 '  </dl>' % (esc(cid), esc(c['date']), esc(c['date']), who(c['created_by'])))
    for img in as_list(c.get('image')):
        parts.append('  <figure class="tcf-reading__figure">\n'
                     '    <img src="%s" alt="Illustration for %s" decoding="async">\n'
                     '  </figure>' % (esc(img), esc(en)))
    parts.append('  <section>\n    <h2>Invitation</h2>\n%s\n'
                 '    <p class="tcf-reading__by">— invitation by %s</p>\n  </section>'
                 % (paragraphs(c.get('invitation', '')), who(c.get('invitation_by', ''))))
    voices = as_list(c.get('affiliate_voices'))
    if voices:
        parts.append('  <section>\n    <h2>Affiliate voices</h2>\n    <ul>\n%s\n    </ul>\n  </section>'
                     % '\n'.join('      <li>%s</li>' % who(v) for v in voices))
    videos = [video_url(v) for v in as_list(c.get('video'))]
    if videos:
        items = []
        for i, v in enumerate(videos, 1):
            label = 'Watch the video' if len(videos) == 1 else 'Watch video %d of %d' % (i, len(videos))
            items.append('      <li><a href="%s">%s</a> (MP4)</li>' % (esc(v), label))
        parts.append('  <section>\n    <h2>Video</h2>\n    <ul>\n%s\n    </ul>\n  </section>' % '\n'.join(items))
    parts.append('</article>')
    pn = []
    if prev_c:
        pn.append('<a href="%s.html" rel="prev">← %s</a>' % (esc(prev_c['id']), esc(prev_c['name_en'])))
    if next_c:
        pn.append('<a href="%s.html" rel="next">%s →</a>' % (esc(next_c['id']), esc(next_c['name_en'])))
    if pn:
        parts.append('<nav class="tcf-reading__pager" aria-label="Previous and next chamber">\n  %s\n</nav>'
                     % '\n  '.join(pn))
    title = '%s · %s · The Chamber · The Civilisation Field' % (zh, en)
    desc = 'Quiet chamber %s (%s · %s), %s, created by %s. Text version.' % (
        cid, zh, en, c['date'], name(c['created_by']))
    return page(title, desc, '\n'.join(parts))


def index_page(chambers):
    # Newest first: by date, then by id, both descending.
    newest_first = sorted(chambers, key=lambda c: (c['date'], c['id']), reverse=True)
    rows = []
    for c in newest_first:
        rows.append('  <li><a href="%s.html"><span class="tcf-reading__zh">%s</span> '
                    '<span class="tcf-reading__en" lang="en">%s</span></a>\n'
                    '    <span class="tcf-reading__row-meta"><time datetime="%s">%s</time> · %s</span></li>'
                    % (esc(c['id']), esc(c['name_zh']), esc(c['name_en']),
                       esc(c['date']), esc(c['date']), who(c['created_by'])))
    body = ('<h1>The Chamber · Quiet Chambers <span class="tcf-reading__zh">靜室</span></h1>\n'
            '<p>%d chambers, as plain text, newest first. Each links to its own page. '
            '<a href="%s">Enter the immersive chamber</a>.</p>\n'
            '<ol class="tcf-reading__list">\n%s\n</ol>' % (len(chambers), IMMERSIVE, '\n'.join(rows)))
    return page('The Chamber · Quiet Chambers (text) · The Civilisation Field',
                'A plain-text list of all %d quiet chambers in The Civilisation Field.' % len(chambers),
                body)


def what_sentence():
    """The Start Here "What" sentence, so llms.txt always matches it word for word."""
    path = os.path.join(ROOT, 'start', 'index.html')
    with open(path, encoding='utf-8') as f:
        m = re.search(r'<p id="what-sentence">(.*?)</p>', f.read(), re.S)
    if not m:
        sys.exit('start/index.html: <p id="what-sentence"> not found')
    return html.unescape(re.sub(r'<[^>]+>', '', m.group(1))).strip()


def sitemap(chambers):
    urls = [''] + IMMERSIVE_PAGES + READING_PAGES + ['chambers/index.html']
    urls += ['chambers/%s.html' % c['id'] for c in chambers]
    body = '\n'.join('  <url><loc>%s</loc></url>' % esc(BASE_URL + u) for u in urls)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!-- Generated by tools/build_chambers.py. Do not edit by hand. -->\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n%s\n</urlset>\n' % body)


def llms_txt(chambers):
    b = BASE_URL
    dates = sorted(c['date'] for c in chambers)
    return """# The Chamber · The Civilisation Field

> %s

The Chamber (畫) is one of the four doors of The Civilisation Field. Main site: %s
Current address: %s (planned: %s).
Reading is not permission to act. Read "For AI readers" before doing anything else.

## Start

- [Start Here](%sstart/): what The Chamber is, why, who, when, where, how, current status.
- [For AI readers](%sfor-ai/): trust boundary. Public pages are read-only information.
- [License](%slicense/): original content is CC BY 4.0; AI and guest responses depend on each case.

## Chambers

- [Text index](%schambers/index.html): all %d quiet chambers as plain HTML (%s to %s), newest first.
- [Quiet Chambers](%spages/page4.html): the immersive gallery (needs JavaScript).
- [Sky Hall](%spages/skyhall.html): 3D gallery (needs JavaScript).
- [Accio](%spages/accio.html): summon one voice's works in 3D (needs JavaScript).

## The Civilisation Field

- [Main Start Here](%sstart/)
- [Main llms.txt](%sllms.txt)

## Optional

- [Sitemap](%ssitemap.xml)
""" % (what_sentence(), MAIN_URL, b, PLANNED_URL, b, b, b, b, len(chambers), dates[0], dates[-1],
       b, b, b, MAIN_URL, MAIN_URL, b)


def main():
    global MEDIA_BASE
    with open(DATA, encoding='utf-8') as f:
        data = json.load(f)
    if isinstance(data, list):          # old format (main repo)
        chambers = data
    else:
        chambers = data['chambers']
        MEDIA_BASE = data.get('media_base', '')
    ids = [c['id'] for c in chambers]
    bad = [i for i in ids if not re.fullmatch(r'ch\d{3}[a-z]?', i)]
    if bad or len(set(ids)) != len(ids):
        sys.exit('chambers.json: unexpected or duplicate ids: %s' % (bad or 'duplicates'))

    os.makedirs(OUT, exist_ok=True)
    written = set()

    def write(name, text):
        with open(os.path.join(OUT, name), 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        written.add(name)

    write('index.html', index_page(chambers))
    for i, c in enumerate(chambers):
        prev_c = chambers[i - 1] if i > 0 else None
        next_c = chambers[i + 1] if i + 1 < len(chambers) else None
        write(c['id'] + '.html', chamber_page(c, prev_c, next_c))

    with open(os.path.join(ROOT, 'sitemap.xml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(sitemap(chambers))
    with open(os.path.join(ROOT, 'llms.txt'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(llms_txt(chambers))

    # Remove pages for chambers that no longer exist in the JSON (generated files only).
    removed = []
    for name in sorted(os.listdir(OUT)):
        if re.fullmatch(r'ch\d{3}[a-z]?\.html', name) and name not in written:
            os.remove(os.path.join(OUT, name))
            removed.append(name)

    print('chambers: %d pages + index.html written to chambers/' % len(chambers))
    print('sitemap.xml (%d URLs) and llms.txt written' % (len(chambers) + len(READING_PAGES) + len(IMMERSIVE_PAGES) + 2))
    if removed:
        print('removed stale pages: ' + ', '.join(removed))


if __name__ == '__main__':
    main()
